### ISSUE TITLE
Package flict for debian

### ISSUE THREAD

**Issue by jeremiah** [vinland-technology/flict#10]
I've started this, will update soon.

**Comment by jeremiah** [comment]
@hesa do you think flict is ready for packaging and distribution to Debian?

**Comment by hesa** [comment]
@jeremiah , I think we can get started.
There are some things that need a change. Even though these are important they are trivial.

**Comment by jeremiah** [comment]
Cool. I'll work on that.

**Comment by jeremiah** [comment]
Which branch for packaging? Master? https://github.com/vinland-technology/flict/branches/all

**Comment by hesa** [comment]
Oh. I prefer a change of the main branch to "main" or "primary". Then perhaps do all devel in a dedicated branch. I will do this and ping you back.

But does Debian wants a branch rather than a release (tar.gz sort of)?

**Comment by hesa** [comment]
Adjustments
* default branch: main
* development branch: devel
* 
@jeremiah, what does Debian need to know about our branches?

**Comment by jeremiah** [comment]
Cool! I'll package the main branch.

Debian doesn't need to know about our branches, I just want to know which branch I should package. I use a tool called git-buildpackage which builds packages out of git. I will create a new branch of main and then also create a Debian packaging branch. Debian's git packaging policy is here: https://dep-team.pages.debian.net/deps/dep14/

I'll likely do all the work in Salsa unless you prefer I do it here?

**Comment by jeremiah** [comment]
I think we need a release to do this properly - otherwise I'll create a tarball as the release but I'll have to make up a version and this might not be a great idea. I'd prefer if you were to cut a release with a version tag as a tarball so that we have good release process. Does that work for you? 

You can use GitHub's release tool which is quite handy: https://github.com/vinland-technology/flict/releases/new

**Comment by hesa** [comment]
We have a version 0.1 now
Will picking up that (git tag or tar.gz/zip) be OK as basis for a deb release?

**Comment by hesa** [comment]
https://github.com/vinland-technology/flict/releases/tag/0.1

**Comment by hesa** [comment]
What meta info is needed?

**Comment by jeremiah** [comment]
When packaging a binary for Debian with git, it is often best to use [Debian's git branching strategy.](http://honk.sigxcpu.org/projects/git-buildpackage/manual-html/gbp.intro.html#gbp.repository) This means that it's likely best we put the version we want to package in Debian's Gitlab instance (Salsa) and call the branches by the conventions; upstream, debian, and pristine tar. 

The metadata needed is copyright, license (including full license text) then some instructions on how to build the binary, where it lives in the file system, dependency information, python version, etc.

**Comment by jeremiah** [comment]
> We have a version 0.1 now
> Will picking up that (git tag or tar.gz/zip) be OK as basis for a deb release?

Yes.

**Comment by jeremiah** [comment]
We can skip the git packaging and just package the .deb from a tarball, but we're using git for development and lots of Debian developers package via git nowadays so might as well package it via git. It's a tiny bit easier to automate as well.

**Comment by hesa** [comment]
I think from now on it should be OK to use git (branch: main) for packaging (kudos to @jens-erdmann and @priv-kweihmann)

**Comment by jeremiah** [comment]
Here's the Debian Intend to Package bug: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=994058.

**Comment by hesa** [comment]
Forgot to ask... anything we can do to help out here?

**Comment by jeremiah** [comment]
Yes, quite likely. :-) I first need to successfully build flict and then build a package so I will come back to the issue tracker with more questions. 

Where are the _latest_ build instructions? Still in INSTALLATION.md?

**Comment by hesa** [comment]
This is dealt with in #123

**Comment by hesa** [comment]
Replaced by #123
