### ISSUE TITLE
Install flict in /usr/local/bin or /usr/bin 

### ISSUE THREAD

**Issue by jeremiah** [vinland-technology/flict#103]
# Feature request

## Minor issue;

When I install flict via pip3 I get a warning;

```
Installing collected packages: boolean.py, license-expression, flict
 WARNING: The script flict is installed in '/home/jeremiah/.local/bin' which is not on PATH.  
 Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location. 
Successfully installed boolean.py-3.8 flict-0.1 license-expression-21.6.14
```
## Describe a tool that might help here

Debian typically proscribes /usr/bin or /usr/local/bin when packaging executable binaries.

## Example data that can be used for tests

From `man hier` 
```
/usr/bin

This is the primary directory for executable programs. 
Most programs executed by normal users which are not 
needed for booting or for repairing the system and which 
are not installed locally should be placed in this directory.
```

**Comment by hesa** [comment]
I tried playing around with the `--target` option (e.g. `pip install --target /tmp/son-volt -e .`) but my Python skills just ain't enough.

@jens-erdmann and @priv-kweihmann, do you know how to install flict to `/usr/bin`?

**Comment by jeremiah** [comment]
@hesa you clearly needed to `pip install --target /tmp/wilco -e && pip play`

**Comment by priv-kweihmann** [comment]
https://stackoverflow.com/a/55388092 should explain how to achieve that -- **BUT** it never has been recommended to mess with the default choices of pip (mainly due to permission issues).
IIRC if one would need everything in /usr/bin (which btw is a permission nightmare, unless you run everything as root), it could be configured when compiling pip itself

**Comment by priv-kweihmann** [comment]
```
  --user                      Install to the Python user install directory for your platform. Typically ~/.local/, or %APPDATA%\Python on Windows. (See the Python
                              documentation for site.USER_BASE for full details.)  On Debian systems, this is the default when running outside of a virtual environment and
                              not as root.
  --root <dir>                Install everything relative to this alternate root directory.
  --prefix <dir>              Installation prefix where lib, bin and other top-level folders are placed
  --system                    Install using the system scheme (overrides --user on Debian systems)
 ```
 
 this is an excerpt from the help of pip on my machine.
 Guess on debian one has to explicitly add `--system` as `--user` is the default :thinking: (to me that's a bit odd - but I'm not a debian user :grin: )

**Comment by jeremiah** [comment]
Personally I prefer the Linux File System Hierarchy over python packaging tools, but I'm old. Fun reading: https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s09.html

/usr/bin and /usr/local/bin are Debian defaults and while not _required_ that is what most python packages do. Debian is one of the distros that follows the FHS closely.

**Comment by jeremiah** [comment]
> https://stackoverflow.com/a/55388092 should explain how to achieve that -- **BUT** it never has been recommended to mess with the default choices of pip (mainly due to permission issues).
> IIRC if one would need everything in /usr/bin (which btw is a permission nightmare, unless you run everything as root), it could be configured when compiling pip itself

It's something inherited from UNIX security I believe to put local binaries in /usr/local/bin or /usr/bin. Having those directories owned by root means only root can create new files under them. When a user runs an executable there, which any user can do because those dirs are group executable, it runs as the user. Programs that run as root are in /usr/sbin/.

**Comment by jeremiah** [comment]
> this is an excerpt from the help of pip on my machine.

+1

> Guess on debian one has to explicitly add `--system` as `--user` is the default thinking

Debian uses install scripts to determine where the binary lives.

> (to me that's a bit odd - but I'm not a debian user grin )

:scream:

**Comment by hesa** [comment]
This problem is part of #10 
Closing this issue.
