### ISSUE TITLE
Test session failure

### ISSUE THREAD

**Issue by jeremiah** [vinland-technology/flict#106]
# Description

While trying to package flict for Debian, I note that large parts of the test suite fail. Part of this is due to the lack of certain dependencies in Debian required for the test suite. Modules like license-expression are not available package in Debian. I also note that the .github files (which appear to be YAML files for some sort of CI), are set to run on Ubuntu. Has flict ever been tested on Debian? 

## Steps for reproduction

Attempt to build a package for Debian on Debian testing.

## Expected behavior

Passing test suite.

## Actual behavior
```
Test session starts (platform: linux, Python 3.9.7, pytest 6.0.2, pytest-sugar 0.9.4)
rootdir: /home/jeremiah/Packaging/clean/flict, configfile: setup.cfg
plugins: sugar-0.9.4, cov-2.12.1, flake8-1.0.6

―――――――――――――――――――――――――――――――――――――――――――――――――――――――――― ERROR collecting .pybuild/cpython3_3.9_flict/build/tests/test_license.py ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
ImportError while importing test module '/home/jeremiah/Packaging/clean/flict/.pybuild/cpython3_3.9_flict/build/tests/test_license.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_license.py:19: in <module>
    import flict.flictlib.license
flict/flictlib/license.py:17: in <module>
    from license_expression import LicenseSymbol
E   ModuleNotFoundError: No module named 'license_expression'

―――――――――――――――――――――――――――――――――――――――――――――――――――――――――― ERROR collecting .pybuild/cpython3_3.9_flict/build/tests/test_project.py ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
ImportError while importing test module '/home/jeremiah/Packaging/clean/flict/.pybuild/cpython3_3.9_flict/build/tests/test_project.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_project.py:20: in <module>
    import flict.flictlib.license
flict/flictlib/license.py:17: in <module>
    from license_expression import LicenseSymbol
E   ModuleNotFoundError: No module named 'license_expression'


----------- coverage: platform linux, python 3.9.7-final-0 -----------
Name                                       Stmts   Miss  Cover   Missing
------------------------------------------------------------------------
flict/__init__.py                              1      0   100%
flict/__main__.py                            240    240     0%   7-518
flict/flictlib/__init__.py                     1      0   100%
flict/flictlib/compat_matrix.py               90     73    19%   28-30, 33-62, 68-70, 73-75, 78-82, 86-105, 108-138
flict/flictlib/compatibility.py              184    184     0%   13-314
flict/flictlib/flict_config.py                14     14     0%   11-30
flict/flictlib/format/FormatInterface.py       0      0   100%
flict/flictlib/format/__init__.py              0      0   100%
flict/flictlib/format/common.py                1      1     0%   14
flict/flictlib/format/dot_format.py           76     76     0%   13-121
flict/flictlib/format/factory.py              21     21     0%   13-40
flict/flictlib/format/format.py               23     23     0%   14-47
flict/flictlib/format/json_format.py          37     37     0%   13-68
flict/flictlib/format/markdown_format.py      38     38     0%   13-73
flict/flictlib/format/text_format.py          61     61     0%   13-95
flict/flictlib/license-group.py               28     28     0%   21-63
flict/flictlib/license.py                    296    292     1%   18-508
flict/flictlib/license_groups.py              31     31     0%   21-73
flict/flictlib/logger.py                      13      8    38%   19-29
flict/flictlib/policy.py                      55     55     0%   13-92
flict/flictlib/project.py                    156    131    16%   36-68, 78-87, 92, 95, 98, 101, 108-125, 132-139, 147-149, 156-175, 183-197, 207-211, 220, 227-233, 236, 249-257, 307-351, 354-356, 361-363, 366
flict/flictlib/relicense.py                   49     34    31%   34-59, 63-76, 80-94
flict/flictlib/report.py                      37     37     0%   13-73
flict/flictlib/return_codes.py                14     14     0%   13-44
flict/flictlib/scancode_licenses.py           52     52     0%   20-92
flict/flictlib/translator.py                  88     69    22%   35-72, 80-91, 95-103, 107-120, 124-147, 151-159
flict/var/__init__.py                          3      0   100%
------------------------------------------------------------------------
TOTAL                                       1609   1519     6%

================================================================================== short test summary info ===================================================================================
FAILED tests/test_license.py
FAILED tests/test_project.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 2 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Results (0.35s):
E: pybuild pybuild:353: test: plugin distutils failed with: exit code=2: cd /home/jeremiah/Packaging/clean/flict/.pybuild/cpython3_3.9_flict/build; python3.9 -m pytest tests
        rm -fr -- /tmp/dh-xdg-rundir-QHnNBkQK

```
## Environment

 | tool    | version    | how to get it       |
 | ------- | ---------- | ------------------- |
 | flict   | 91-move-makefile branch | `flict --version`   |
 | python3 | 3.9.7 | `python3 --version` |
 | os      | Debian testing | `cat /etc/os-release` on GNU/Linux      |

**Comment by priv-kweihmann** [comment]
Did you install all the required dependencies? aka `pip3 install -r requirements.txt && pip3 install -r requirements-dev.txt`

**Comment by priv-kweihmann** [comment]
BTW when installing it via pip at least the minimum runtime dependencies are installed automatically - I don't know how you installed the tool (I guess with something like `python3 setup.py install`) ... for all **non**-pip installations the requirements from `requirements.txt` needs to be installed manually

**Comment by priv-kweihmann** [comment]
It's also possible to run pip from a git clone (`pip3 install .` - from the clone dir)

**Comment by jeremiah** [comment]
On a Debian system, the packaging system can only rely on dependencies that are already in Debian. This ensures that you can install a complete system from CD or other media for example. Debian doesn't allow one to download software from the Internet because the target system might not have a network connection. So my feeling is that Debian packaging of flict requires one of these choices;

1. Package for Debian all the dependencies
2. Remove the test suite from the Debian package
3. Determine how other python packages in Debian manage pip dependencies

3 is likely to be the best, but 2 is a real possibility. Doing 1 would require lots of extra work. I'll investigate 3 but I will also look at how Debian does python testing since they use a somewhat different system that allows for test suite specific dependency resolution which *may* offer us a way out of this situation.

**Comment by jeremiah** [comment]
IMHO testing flict builds on Debian as the target system often highlights these problems early so they're easier to resolve for other distros. I'd avoid using Ubuntu as your main build target because a) it's not all free software, b) it is Debian derived. Might as well test on the reference system.

**Comment by hesa** [comment]
Addressing the choices above:

1. Package for Debian all the dependencies
2. Remove the test suite from the Debian package
3. Determine how other python packages in Debian manage pip dependencies

(1) Provide debs for the package `license-expression` as in ´requirements.txt`, but not the packages in `requirements-dev.txt` sounds good. 

(2) flict will not work without `license-expression`. We aim at using it more, so it is not an option to do our own such module.

(3) my guess is, as proposed in (1)

**Comment by hesa** [comment]
Suggestion (1) can now be found in #123
