### ISSUE TITLE
 Add outbound candidates to report

### ISSUE THREAD

**Issue by hesa** [vinland-technology/flict#111]
# Feature request

A compatibility report currently includes:

  "licensing": {
    "outbound_candidates": [
      "GPL-2.0-only",
      "GPL-3.0-only"
    ]
  }

Suggestion: keep outbound candidates in policy report to link compatibility report and policy report

## Is your feature request related to a problem? Please describe.

Useful for compliance officers

**Comment by jens-erdmann** [comment]
This is not referring to https://github.com/vinland-technology/flict/blob/main/flict/flictlib/report.py#L59 correct?

**Comment by hesa** [comment]
Policy not needed anymore. 
With the rewrite this information should be available. 

```
$ flict verify -s example-data/freetype-2.9.spdx.json -sd example-data/ | jq -r .packages[0].outbound_licenses[]
Zlib
Libpng
FTL
GPL-2.0-or-later
```
