### ISSUE TITLE
 Add git/homepage to all reports

### ISSUE THREAD

**Issue by hesa** [vinland-technology/flict#113]
# Feature request

Add git/homepage to all reports

## Is your feature request related to a problem? Please describe.

none

**Comment by kkrolczyk** [comment]
Apparently policy report was removed from flict, but 

`flictlib/format/text_format.py -> format_policy_report()` remained, as well as confusing policy-report main option... and entry in EXAMPLES.md ...

**Comment by hesa** [comment]
EXAMPLES: https://github.com/vinland-technology/flict/pull/232

**Comment by hesa** [comment]
format_policy_report: removed in branch `hesa-fix-issue-147`

**Comment by hesa** [comment]
See: https://github.com/vinland-technology/flict/pull/233

**Comment by hesa** [comment]
https://github.com/vinland-technology/flict/pull/233
