### ISSUE TITLE
Use translations from LDBCollector

### ISSUE THREAD

**Issue by hesa** [vinland-technology/flict#125]
# Feature request

We need to add translations (e.g. `GPL3` -> `GPL-3.0-only`). As discussed here https://github.com/maxhbr/LDBcollector/issues/4 we could make use of translations as provided by https://github.com/maxhbr/LDBcollector

_**Note**: the list above contains duplicates_

## Is your feature request related to a problem? Please describe.

Some build systems and other tool use non SPDX license expression, so if we want to go automatic we need to translate a license expression in to an SPDX identifier (if such exists).

## Describe a tool that might help here

Write a simple JSON parser to get the unproblematic license translations from: https://github.com/maxhbr/LDBcollector/issues/4

## Example data that can be used for tests

https://github.com/maxhbr/LDBcollector/issues/4

**Comment by priv-kweihmann** [comment]
I have mixed feelings about getting another direct dependency into the mix - In my opinion we should use the code from either `license-expression` or that module mentioned **but** not the data. the data should be stored in our scope, what makes it adjustable to our purposes way more easily

**Comment by hesa** [comment]
Since the stuff in LDB originates from Scancode I figure it is better to discuss things there. I will join their next weekly meeting: https://github.com/nexB/aboutcode/wiki/MeetingMinutes

Hoping @pombredanne and friends allow us to hijack part of the meeting.

**Comment by hesa** [comment]
Closing this issue
