### ISSUE TITLE
Change default format to text

### ISSUE THREAD

**Issue by hesa** [vinland-technology/flict#129]
# Feature request

Today the output is by default  done in JSON. This is good when interacting with other programs but works poorly with humans. 

Suggesting to use `text` as default format. And leave `JSON` and `markdown` as avilable (via command line options) just as before.

## Is your feature request related to a problem? Please describe.

When using flict in my daily work I find it annoying to go `flict verify -of text  -le Apache-2.0 AND GPL-3.0-only` rather than `flict verify  -le Apache-2.0 AND GPL-3.0-only`

**Comment by priv-kweihmann** [comment]
I suggest a different approach, let's bring in a user specific config file (like .bashrc) that configures that behavior, cuz I think I want json to be the default
