### ISSUE TITLE
Overlook return codes for verify and policy-report

### ISSUE THREAD

**Issue by hesa** [vinland-technology/flict#147]
# Return codes for verify and policy report shall be useful in CI

1. Update spec of return codes for `verify` with:
* `1` - no outbound candidates found

2. Update spec of return codes for `policy-report` with:
* `2` - outbound licenses found, but only using _avoid_ licenses
* `3` - outbound licenses found, but only using _denied_ licenses

3. Add policy files to fit the above spec

4. Implement the above (in code)

## Is your feature request related to a problem? Please describe.

When using flict in a CI or some other automated process we need to provide clear return  values to make it easy for computers to understand the result.

## Example data that can be used for tests

1. Can be tested with:
```
flict -nr verify -le GPL-2.0-or-later and Apache-2.0; echo $?
{"license_expression": " GPL-2.0-or-later and Apache-2.0", "compatible": false, "outbound_candidate": []}
0
```
which instead should return `1`

```
flict -o europe-report.json verify -pf example-data/europe-small.json 
flict policy-report -crf europe-report.json -lpf example-data/some-policy-file.json
```

**Comment by kkrolczyk** [comment]
1. i guess this is quite outdated.

2. Also, such command can be found in the examples:
`flict -o europe-report.json verify -pf example-data/europe.json`
however `-pf` is not supported anymore. 

3. `example-data/europe.json`  claims to be used in tests, but only `example-data/europe-small-bad.json` is currently being used in tests

**Comment by hesa** [comment]
Outdated: yes

Return codes now:
```
    RET_SUCCESS = (0, "Success")
    RET_INTERNAL_ERROR = (1, "Internal error")
    RET_MISSING_ARGS = (5, "Missing arguments")
    RET_INVALID_PROJECT = (10, "Invalid project")
    RET_INVALID_EXPRESSSION = (11, "Invalid expression")
    RET_FILE_NOT_FOUND = (12, "File not found")
    RET_INVALID_ALIAS_FILE = (13, "Invalid alias file")
    RET_INVALID_LICENSE_PREFERENCE = (13, "Invalid license preferences")
```
"-pf" fixed in https://github.com/vinland-technology/flict/commit/571a2d624fdc74e8c92c1da1891fa71954662223

I suggest, at some time, move test files to the tests dir and have useful examples (as the name suggests) in the examples directory. Removed the europe file.

**Comment by hesa** [comment]
See: https://github.com/vinland-technology/flict/pull/233

**Comment by hesa** [comment]
Closed with https://github.com/vinland-technology/flict/pull/233
