### ISSUE TITLE
Move code out of __main__.py

### ISSUE THREAD

**Issue by jens-erdmann** [vinland-technology/flict#149]
To be able to test all functions of flict most of the code in __main__.py should be moved out. It should only contain arg parser code and simple functions to by called by it.
Actual business logic should be moved into a different file so we can import it in our test files. I am not sure if there is an impl paradigm in python but maybe we could just have such a class for now.

**Comment by hesa** [comment]
Do we need a class? Functions, as it is now, ought to be OK?

**Comment by jens-erdmann** [comment]
> Do we need a class? Functions, as it is now, ought to be OK?

It might be easier to handle with a class but I would be ok to not have one.

**Comment by jens-erdmann** [comment]
Fixed with #157
