### ISSUE TITLE
Need a new release

### ISSUE THREAD

**Issue by jeremiah** [vinland-technology/flict#16]
Debian packaging needs a tarball and a version.

#10

**Comment by hesa** [comment]
I know how to do c/c++ pkgs ... but have no clue about Python

**Comment by jeremiah** [comment]
I don't think we need either a C/C++ package or a python package - we can just tar up the source code. I'll double check.

**Comment by jeremiah** [comment]
Yeah - we have a beta pre-reelase; https://github.com/vinland-technology/flict/releases/tag/v0.1

**Comment by jeremiah** [comment]
I can start testing with this: https://github.com/vinland-technology/flict/releases/tag/v0.1
The testing is mostly; 

- download the release
- build the software on my system
- package for debian
- move the result into Debian's Salsa tool -- https://salsa.debian.org/
