### ISSUE TITLE
CompatMatrixStatus should be its own module

### ISSUE THREAD

**Issue by jens-erdmann** [vinland-technology/flict#172]
We have several places where CompatMatrixStatus is interpreted into different formats. It should be moved into its own module with all these interpretations.

**Comment by priv-kweihmann** [comment]
I didn't find that many conversions of that enum... can you name a few?

**Comment by jens-erdmann** [comment]
Hmm. Seems like I am mixing this up with CompatibilityStatus.

**Comment by jens-erdmann** [comment]
flict translates between CompatibilityStatus and CompatMatrixStatus. It also translates between CompatMatrixStatus <> "JSON" string <> CompatibilityStatus. These translations are shared between compat_matrix.py and compatibliity.py.
I have no better solution for this as of now but I still think this is not optimal.

**Comment by kkrolczyk** [comment]
@jens-erdmann it looks as `CompatMatrixStatus` does not exist anymore. I guess this could be closed in such case.
