### ISSUE TITLE
license compatibility matrix not public

### ISSUE THREAD

**Issue by robbiemorrison** [vinland-technology/flict#199]
The **license compatibility matrix** cited on the GitHub landing page returns a 403 error (you don't have permission to access) for me as an ordinary user:

- https://www.osadl.org/fileadmin/checklists/matrix.html

You may need to change the **access permissions** for that file, therefore?

**Comment by TheKanter** [comment]
+1 just discovered this.

**Comment by hesa** [comment]
README now says:

To check compatibility between two licenses flict is using [osadl-matrix](https://github.com/priv-kweihmann/osadl-matrix) which is using [OSADL](https://www.osadl.org/)'s [matrix.json](https://www.osadl.org/fileadmin/checklists/matrix.json) as found in [Open Source License Checklists](https://www.osadl.org/OSADL-Open-Source-License-Checklists.oss-compliance-lists.0.html)

**Comment by robbiemorrison** [comment]
Thanks team!
