### ISSUE TITLE
flict fails without a HOME environment variable

### ISSUE THREAD

**Issue by garb-ma** [vinland-technology/flict#251]
# Description

First of all, thank you for your bug report. Please fill out below sections (if applicable) to help us fix the issue as good and fast as possible.

## Steps for reproduction

Running flict w/o having an environment variable named HOME.

The script flict/flictlib/flict_config.py contains the following: 

```
def read_user_config():
    for path in [
        os.environ.get('FLICT_USERCONFIG'),
        os.path.join(os.environ.get('HOME'), '.flict.cfg'),
    ]:
        try:
            with open(path) as i:
                return json.load(i)
        except Exception:  # noqa: S110 - it's okay ignore all errors here
            pass
    return {}
```

This function fails because a None is returned to os.path.join, which results in a TypeErrror.
```
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

## Expected behavior

The script should work w/o having to set an environment variable manually.

## Environment

 | tool    | version    | how to get it       |
 | ------- | ---------- | ------------------- |
 | flict   | 1.0.9 | `flict --version`   |
 | python3 | 3.7.12 | `python3 --version` |
 | os      | windows | n.a.                |

I am using flict in a conda environment on Windows.

**Comment by priv-kweihmann** [comment]
We can fix the issue itself, but I’m not sure how helpful that will be - Windows support is currently not planned in any way - As to be seen in the metadata only POSIX Linux is supported - Maybe it could be an option for you to switch to working on WSL2 or something.
Anyway the reported bug should be fixed, I’ll take a look into that later on

**Comment by priv-kweihmann** [comment]
@garb-ma latest version does contain a fix to this issue - please give it a try and close this issue, if your problem has been fixed

**Comment by garb-ma** [comment]
@priv-kweihmann
Have only now been able to test it with version 1.012. The problem no longer occurs. Thanks for your effort.
