### ISSUE TITLE
Feature Request: Flict uses OSADL Matrix and for some of the licenses that are not part of OSADL Matrix yet, it becomes an issue to resolve the compatibility. Example: GPL v2.0 w/ OpenSSL exception. It definitely will be a boon to have a way around to deal with such typical licenses that are common and cannot find an entry or equivalent entry in the OSADL matrix as of date.  

### ISSUE THREAD

**Issue by Sathyasundarp** [vinland-technology/flict#252]
# Feature request

First of all, thank you for your interest in this project. Please fill out below sections (if applicable) to help us understand your idea better.

## Is your feature request related to a problem? Please describe.

> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

## Describe a tool that might help here

> Post an URL to the tool's repository

## Example data that can be used for tests

> Post an URL or a text dump of data that can be used to test the new feature

**Comment by hesa** [comment]
Question: Is it possible to add license manually yourself?

Yes, it is possible. However, the documentation[0] perhaps needs a bit more attention. I will try to add a complete example and also some words how to check your additions.

[0] https://github.com/vinland-technology/flict/blob/main/SETTINGS.md (see Extending the license db)

**Comment by priv-kweihmann** [comment]
To be precise this section https://github.com/vinland-technology/flict/blob/main/SETTINGS.md#extending-the-license-db does describe how to achieve what you asked for @Sathyasundarp .
Does that solve your issue?

**Comment by Sathyasundarp** [comment]
Hi @hesa @priv-kweihmann: Sorry for not being able to respond earlier. Thank you so much, yes, this clarifies the position. I shall try it out and will get back should I need further support. Cheers, Sathya

**Comment by hesa** [comment]
To extend the license matrix you can use https://github.com/hesa/elmat

Example: you would like to extend the license matrix with FooBar like this:
FooBar can use BSD-3-Clause: yes
FooBar can use `Apache-2.0: no

Create a file, `foobar-license.json`, with the following content:
```
{
    "extended_licenses": {
	"FooBar": {
	    "BSD-3-Clause": "Yes",
	    "Apache-2.0": "No"
	}
    }
}
```

Then merge your additions with elmat's:

```
elmat --license-file foobar-license.json -of json merge > elmat-license-matrix.json
```

And now, you can use the extended matrix (file) like this:

```
$ flict -of text -lmf elmat-license-matrix.json verify -ol FooBar -il BSD-3-Clause
Yes
```
