### ISSUE TITLE
Rework reporting and avoid usage of print statements

### ISSUE THREAD

**Issue by priv-kweihmann** [vinland-technology/flict#29]
The output stream shall be configurable (and not limited to `sys.stdout`).

- add option to argparse for the output stream (default sys.stdout)
- rework statements like https://github.com/vinland-technology/flict/blob/8ead8d8d6a79cb3a1b7efd9b5d0d96901b422f3c/flict/__main__.py#L377
- activate hard rule in flake8 linter to fail on print statements

**Comment by hesa** [comment]
@priv-kweihmann fixed with #45
