### ISSUE TITLE
Enable flake8 linter in pytest

### ISSUE THREAD

**Issue by priv-kweihmann** [vinland-technology/flict#30]
currently that is disabled, as there are way too many warnings.

- fix as many warnings as possible
- add global suppression for things we don't want in this project (@hesa any type of preference for a style guide of this project? pep8? none? something customized?)
- enable flake8 in pytest options

**Comment by hesa** [comment]
Style guide: you decide

**Comment by priv-kweihmann** [comment]
okay, so I choose none and disable all style guide related IDs
