### ISSUE TITLE
1.0.32 spam

### ISSUE THREAD

**Issue by kkrolczyk** [vinland-technology/flict#305]
# Description

Running any command seems to generate lots of spam in addition to normal results

```WARNING:root:{'Compatibility*': 'zlib-acknowledgement', ....```

Spam actually originates from osadl-matrix dependency - PR created, see https://github.com/priv-kweihmann/osadl-matrix/pull/105

## Steps for reproduction

pip install flict
flict -of dot display-compatibility BSD-3-Clause MIT GPL-2.0-only 

## Expected behavior

Just the result, as described in example

## Environment

 | tool    | version    | how to get it       |
 | ------- | ---------- | ------------------- |
 | flict   | 1.0.32 | `flict --version`   |
 | python3 | 3.10.6 | `python3 --version` |

**Comment by priv-kweihmann** [comment]
Fixed in release 1.0.33 - thanks for noticing and the fix
