### ISSUE TITLE
(c) setup.py faulty

### ISSUE THREAD

**Issue by hesa** [vinland-technology/flict#31]
(c) is Konrad's

**Comment by priv-kweihmann** [comment]
I don't insist on it - just leave it for now.
But it would be nice to have it documented in a contribution guide, how to deal with new CR holders...
for cases such as
- file modification (add/remove CR info)
- new files (whom to add)

**Comment by priv-kweihmann** [comment]
Maybe we could add a automatic check for that, using git blame `git log --pretty=format:"%an%x09" <file> | sort | uniq` and double check this with the modified files of a PR

**Comment by hesa** [comment]
I will insist, staring here:

https://github.com/vinland-technology/flict/tree/3-contribution-guidelines
