### ISSUE TITLE
Verify option is not working

### ISSUE THREAD

**Issue by vaniacer** [vinland-technology/flict#330]
# Description

Verify option throws an error.

## Steps for reproduction

I'm trying to test 'verify' option as shown in [presentation](https://www.sfscon.it/talks/checking-license-compatibility-with-flict/)
`flict -of text verify -le Apache-2.0 AND GPL-3.0-only AND MIT`

## Expected behavior

![изображение](https://github.com/vinland-technology/flict/assets/18072680/7cd110b2-1dda-4777-a24b-a179e5fb6532)

## Actual behavior

```
$ flict -of text verify -le Apache-2.0 AND GPL-3.0-only AND MIT
usage: flict [-h] [--license-matrix-file LICENSE_MATRIX_FILE] [--licenses-denied-file LICENSES_DENIED_FILE]
             [--licenses-preference-file LICENSES_PREFERENCE_FILE] [--alias-file ALIAS_FILE] [--license-info-file LICENSES_INFO_FILE] [-el] [-nr]
             [-o OUTPUT] [-of OUTPUT_FORMAT] [-v] [-cc LICENSES [LICENSES ...]] [-ol OUTBOUND_LICENSES] [-V] [-dl]
             {verify,simplify,list,merge,display-compatibility,outbound-candidate,policy-report} ...
flict: error: unrecognized arguments: -le Apache-2.0 AND GPL-3.0-only AND MIT
```

## Environment

 | tool    | version    | how to get it       |
 | ------- | ---------- | ------------------- |
 | flict   | 1.1.4 | `flict --version`   |
 | python3 | 3.8.10 | `python3 --version` |
 | os      | Linux Mint 20 | `lsb_release -a`  |

> add additional tools you used and their versions here

## Additional logs

Same error if args are enclosed in quotes and with other licenses:
```
$ flict -of text verify -le "Apache-2.0 AND GPL-3.0-only AND MIT"
usage: flict [-h] [--license-matrix-file LICENSE_MATRIX_FILE] [--licenses-denied-file LICENSES_DENIED_FILE]
             [--licenses-preference-file LICENSES_PREFERENCE_FILE] [--alias-file ALIAS_FILE] [--license-info-file LICENSES_INFO_FILE] [-el] [-nr]
             [-o OUTPUT] [-of OUTPUT_FORMAT] [-v] [-cc LICENSES [LICENSES ...]] [-ol OUTBOUND_LICENSES] [-V] [-dl]
             {verify,simplify,list,merge,display-compatibility,outbound-candidate,policy-report} ...
flict: error: unrecognized arguments: -le Apache-2.0 AND GPL-3.0-only AND MIT

$ flict -of text verify -le MIT AND BSD-3-Clause
usage: flict [-h] [--license-matrix-file LICENSE_MATRIX_FILE] [--licenses-denied-file LICENSES_DENIED_FILE]
             [--licenses-preference-file LICENSES_PREFERENCE_FILE] [--alias-file ALIAS_FILE] [--license-info-file LICENSES_INFO_FILE] [-el] [-nr]
             [-o OUTPUT] [-of OUTPUT_FORMAT] [-v] [-cc LICENSES [LICENSES ...]] [-ol OUTBOUND_LICENSES] [-V] [-dl]
             {verify,simplify,list,merge,display-compatibility,outbound-candidate,policy-report} ...
flict: error: unrecognized arguments: -le MIT AND BSD-3-Clause

```

**Comment by hesa** [comment]
Despite that the image you attached implies that recording was made last month, it was actually made 2021. The syntax then didn't help in many use cases. So now, flict checks, among other things, licenses the following way, is the outbound license compatible with the inbound. This is (probably) what most developers/organisations/companies need.

Using latest flict==1.1.4 as an example:

Checking if you can use the outbound license "GPL-2.0-only" if your inbound are "Apache-2.0 AND GPL-3.0-only":
```
$ flict -of text verify -il Apache-2.0 AND GPL-3.0-only AND MIT -ol GPL-2.0-only
No
```

You can also, as another example, let flict suggest outbound candidates for you:
```
$ flict -of text outbound-candidate Apache-2.0 AND GPL-3.0-only AND MIT 
GPL-3.0-only
```

**Comment by hesa** [comment]
@ohnewein, look at the attached screenshot of sfscon.it. It looks as if I talked a month ago.

**Comment by ohnewein** [comment]
> @ohnewein, look at the attached screenshot of sfscon.it. It looks as if I talked a month ago.
>  

I see. This is because the header bar on the website always displays the date of the newest SFSCON.

And, because you look the same since many years.

But you can lookup in your profile site the years of your contributions to SFSCON:

https://www.sfscon.it/speakers/henrik-sandklef/

We will see, if we can find some way to better display the year of past talks.

Thanks for your feedback and for your many contributions to SFSCON!
