### ISSUE TITLE
Restructure command line 

### ISSUE THREAD

**Issue by hesa** [vinland-technology/flict#43]
# Background

Flict has been developed in a rather chaotic way and it's about time to end that and get structured. Before looking at the code I suggest to list the use cases we have and from that implement an easier to understand command line.

Here are some thoughts on the above....

# Use cases

Here are some use cases that I have myself:

1. verify license compatibility for:

    * project (with dependencies), results in a compatibility report

    * a license expression (e.g. `MIT and GPL-2.0-or-later`)
    
2. create compatibility chart between licenses, presented as

    * a graph 

    * a table

3. suggest outbound license for a license expression
    
4. create policy report - input is a compatibility report and a license policy applied

# Sub commands

The above use cases will be turned into sub commands:

1. `verify`

2. `display-compatibility` (and `d-c`?)

3. `suggest-outbound`  (and `s-o`?)

4. `policy-report` 

# Options and arguments

These sub command are suggested to have

* common options (e.g `--verbose`, `output-format`, `output`) 

* specific options (`--graph` for (2))

* arguments (e.g. `<license expression>` for (3))

# Examples

Some examples to hopefully make things easier to follow:

### Project (with dependencies)

Project (with dependencies) as stored in `cairo.json` with `verbose` mode, stored in `cairo-report.json`

```
flict --verbose -o cairo-report.json verify --project cairo.json 
```

### License expression

License expression, "MIT and GPL-3.0-or-later" and output to stdout in markdown format

```
flict --output-format markdown verify "MIT and GPL-3.0-or-later"
```

### as a graph

```
flict --output license.dot --output-format display-compatibility MIT GPL-3.0-or-later --graph
```

Which will create the graph in dot format, which can be turned in to pdf like this:

```
dot -Tpdf  license.dot -O
```

### as a table

```
flict --output-format pdf display-compatibility MIT GPL-3.0-or-later --table
```

## 3 Suggest outbound

Suggest outbound license for a license expression, in markdown format on stdout

```
flict suugest-outbound "MIT and GPL-3.0-or-later or Apache-2.0" --output-format markdown
```

## 4 Create policy report

Create policy report, compatibility report as input and with license policy applied

Assuming we have the report, `cairo-report.json`, from previous example
```
flict --output-format JSON --output cairo-policy-report.json policy-report --report cairo-report.json
```

# Questions

## Mixing

Is it a good thing to use common and sub command options like this

```
flict --verbose verify --project cairo.json
```

or is it better (easier to understand what is option sub command and argument):

```
flict verify --verbose --project cairo.json
```

**Comment by jeremiah** [comment]
This is great, very useful.
