### ISSUE TITLE
Installation.md: Adding PATH to bashrc 

### ISSUE THREAD

**Issue by hesa** [vinland-technology/flict#8]
Use $$ instead of $ when adding to bashrc

**Comment by priv-kweihmann** [comment]
bash shouldn't even be used at all - IMHO there is no need to invoke bash while running the tool.
at what point do we need bash?

**Comment by hesa** [comment]
Earlier flict had options go generate `pdf` and `html`. This was done from the `markdown` output using `pandoc` via a wrapper script. Now, thanks to you @priv-kweihmann, flict installs nicely without any bash script. 

I think adding a bash wrapper would:
1. make it easy to generate pdf, html etc
2. add to complexity

**2** is more important so, let's close this one
