### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by jens-erdmann** [vinland-technology/flict#88]
As we discussed recently, a docker file could be created to enhance the user experience and lower the entrance.

There was also the idea to improve testing workflow by using docker and maybe a rudimentary install script.

I created two branches for potential docker file solutions.
Solution 1: Very simple Dockerfile + very simple install.sh that could be used in CI as well.
https://github.com/vinland-technology/flict/tree/install-script
Solution 2: Fancy multi-stage Dockerfile
Can produce testing on demand.
https://github.com/vinland-technology/flict/tree/multi-stage-docker

**Comment by jeremiah** [comment]
FWIW I use Docker for Debian packaging and testing, so I'd probably reuse the Dockerfile.

**Comment by jens-erdmann** [comment]
Feel free to add your opinion if you got a preference.

**Comment by hesa** [comment]
I have to little experience in Docker to decide. @jens-erdmann - your call to decide :)

**Comment by priv-kweihmann** [comment]
Finally found the time to add my 2 cents.
I personally like https://github.com/vinland-technology/flict/tree/multi-stage-docker more.

**but** it is still missing a few bits and pieces...

- the container needs to be referenced in the CI pipelines somehow
- documentation is missing on this one
- the TODOs have to be resolved
- I wonder how to map local files into the container (I guess that needs to be documented)
- maybe it's worth adding also a docker-compose file, as users tend to use docker-compose nowadays
- we might need to specify the the base container more precisely (as python:3-slim is a moving target always pointing to the very latest python version) - I personally would rather pick 3.10-slim-buster or 3.9-slim-buster as a basis

but so far I think we don't necessarily need an install script.
I'd happy if we can push that forward

**Comment by jens-erdmann** [comment]
We introduced a script in #154 to set up flict inside of a stock python container. We settled on this solution right now and agreed to not have a dedicated docker image for flict as of now. This might change in the future.
