### ISSUE TITLE
Add grouping of licenses

### ISSUE THREAD

**Issue by hesa** [vinland-technology/flict#89]
Grouping permissive licenses to a new "group", typically called "Permissive", would make it possible to reduce the number of possible combinations. A simple license expression like `MIT and BSD-3-Clause and BSL-1.0` could be reduced to `Permissive`.

This will probably lead to reduced complexity when looking at (example from Cairo with deps): 
```
Zlib and Libpng and (FreeType or GPLv2+) and BSD-3-Clause and MIT and MIT-style and MIT and PD and MIT and MIT-style and PD and (MPL-1.1 or LGPLv2.1) and BSD-3-Clause and (LGPLv2.1+ and BSD and PD) and MIT 
```

could be simplified  to 
```
BSD-3-Clause AND LGPLv2.1+ AND Libpng AND MIT AND MIT-style AND PD AND Zlib AND (FreeType OR GPLv2+) AND (LGPLv2.1 OR MPL-1.1)
```

which, using groups, could be reduced to:
```
LGPLv2.1+ AND Permissive AND (LGPLv2.1 OR MPL-1.1)
```

May not be a massive achievement, but it also opens up for using the (unsigned long) long list of licenses classified as Permissive over at https://scancode-licensedb.aboutcode.org/ (ping @pombredanne)

**Comment by pombredanne** [comment]
@hesa you could very much use the license-expression library for this:
1. scan and get an expression
2. parse the expression
3. apply a substitution using a table https://github.com/bastikr/boolean.py/blob/5954297a0babca994fd1eeccb09e19eda172e3fa/boolean/boolean.py#L635
4. render back the expression (possibly as SPDX)

**Comment by hesa** [comment]
Thanks  @pombredanne 

This is related to: https://github.com/maxhbr/LDBcollector/issues/4 (this issue was about providing support for using the db from @maxhbr for translating license name not being SPDX)

**Comment by pombredanne** [comment]
@hesa re:

> Zlib and Libpng and (FreeType or GPLv2+) and BSD-3-Clause and MIT and MIT-style and MIT and PD and MIT and MIT-style and PD and (MPL-1.1 or LGPLv2.1) and BSD-3-Clause and (LGPLv2.1+ and BSD and PD) and MIT 

where does this come from?

**Comment by hesa** [comment]
From a script compiling licenses from a package and its dependencies . I tweaked the result a bit. Why do you ask?

@pombredanne - in the scancode license db you, rightfully so, classify Apache-2.0 as permissive. However it is not compatible with the gpl2 family. This means flict cant use your permissive classification to determine if a license can "use" software under a permissive license (since at least one of your permissive is not compatible with *gpl-2*).

So I see a need to add a bit of information to your license db before it can be used (accurately) by flict to determine compatible between two licenses. I am interested in looking in to this.. but I think this would need input from you as well. Work is fun :) Waddya say?

**Comment by pombredanne** [comment]
> From a script compiling licenses from a package and its dependencies . I tweaked the result a bit. Why do you ask?

Would this be a script that get License: lines from Debian copyright file? I am asking because the "symbology" used there is neither SPDX nor ScanCode.

**Comment by pombredanne** [comment]
> So I see a need to add a bit of information to your license db before it can be used (accurately) by flict to determine compatible between two licenses. I am interested in looking in to this.. but I think this would need input from you as well. Work is fun :) Waddya say?

Sure.

**Comment by hesa** [comment]
> > From a script compiling licenses from a package and its dependencies . I tweaked the result a bit. Why do you ask?
> 
> Would this be a script that get License: lines from Debian copyright file? I am asking because the "symbology" used there is neither SPDX nor ScanCode.

The license expression (think I may have changed AND/& OR/|) comes from Yocto, compiled using https://github.com/vinland-technology/compliance-utils. More details here: https://software-compliance.se/posts/2021-02-12/ ... but the interesting part for you is: **the license expressions come from Yocto recipes**

**Comment by hesa** [comment]
With the new implementation you can add your own licenses (e.g. `Permissive`) and use aliases to let `MIT-style` and `x11-keith-packard` be aliases for `Permissive`. When flict see `MIT-style` it will check compatibility using the self defined `Permissive`. 

Closing issue
