### ISSUE TITLE
Do you really need a Makefile with a python package?

### ISSUE THREAD

**Issue by jeremiah** [vinland-technology/flict#91]
There are not a lot of python packages in Debian that use a Makefile to run tests. Though I've only looked at three or four, I can't seem to find one. Is this a "pythonic" approach to use a Makefile for tests? I see a different approach in Debian that has the power to declare separate dependencies for tests as well.

**Comment by hesa** [comment]
Nah, I guess this is a sign of my background with Makefiles and the autotools. It's in my fingers to write `make`. 

This Makefile is useless and can/should be removed since it may (obviously did) confuse folks.

**Comment by jeremiah** [comment]
It confused me. What happened was that using standard Debian tools to build a .deb, it called the Makefile, which in turn called the tests, which in turn needed all the requirements-dev.txt dependencies. This is totally fine of course, it's just that it might be easier for whoever wants to build and package to have a single requirements file and maybe a single build system. (I know it's python so there are many build systems. :)

**Comment by hesa** [comment]
If I find a Makefile in a repo I'd go "make". I will (re)move it

**Comment by jeremiah** [comment]
heh, me too. But that is exactly what breaks because it runs the test suite and won't find pytest unless you already have pytest installed.

**Comment by hesa** [comment]
Pytest is in requirement-dev.txt

How to make deb tools adapt to our setup?

**Comment by jeremiah** [comment]
> Pytest is in requirement-dev.txt

Yep.

> How to make deb tools adapt to our setup?

This is the question. From the Debian side, it is the same question but in reverse; how to make the application code adapt to Debian setup? Unfortunately, my experience is largely with perl in Debian though I've done some GNOME packaging as well. The thing about perl and GNOME vs. python packaging is that they each use different tools and policy and have different teams maintaining them. From what I understand, we'll likely be most successful if we follow this: https://wiki.debian.org/Python/GitPackaging

**Comment by hesa** [comment]
Do you need any new stuff/changes in flict to use this way of packaging?

**Comment by jeremiah** [comment]
I think what would be easier for me is a consolidated requirements.txt file. Aside from that I'm not sure what's needed aside from doing things the Debian way.

**Comment by hesa** [comment]
The req file without -dev is for users

The one with -dev is for developers. Without all test deps.

**Comment by hesa** [comment]
So, I think you can go for:
* requirements.txt and skip tests
Or
* requirements-dev.txt if you want to do tests

**Comment by jeremiah** [comment]
But that's just it - you can't not run the tests, they're part of the build. And you have to build a binary to have a deb package. So while I see the usefulness of breaking out the test dependencies into a separate file, in building a deb the tests are included in the build so effectively we need all those dependencies. It's just easier to have it in one file, more DRY as well.

**Comment by hesa** [comment]
BTW; the Makefile is in this branch (to be merged in https://github.com/vinland-technology/flict/pull/97) "pining for the fjords" so you give that a shot: https://github.com/vinland-technology/flict/tree/91-move-makefile

I get your point, but adding all the requirements (see below) is in my opinion not "Simply the best" for "Common people":
```
flake8-fixme >=1.1.0, <3.0.0
flake8-print >=4.0.0, <6.0.0
pytest >=6.2.0, <8.0.0
pytest-bandit >=0.6.0, <2.0
pytest-cov >=0.6.0, <3.0.0
pytest-flake8 >=1.0.0, <3.0.0
pytest-freeze-reqs >=0.2.0, <2.0.0
pytest-icdiff >=0.5, <2.0
pytest-random-order >=1.0.0, <3.0.0
pytest-socket >=0.4.0, <2.0.0
pytest-sugar >=0.9.0, <2.0.0
pytest-tldr >=0.2.0, <2.0.0
twine >=3.4.0, <5.0.0
wemake-python-styleguide >=0.15.2, <2.0.0
```

Is there something we can add to force the deb tools to "Do the right thing".

...sorry for all the quoting.

**Comment by jeremiah** [comment]
I think most "Common people" will install via their system's package manager. That is to say you'll see an exponential increase in users if you package for Debian and Ubuntu. Users trust APT to install things. 

With that said, I think there are things that we can do to make it more pythonic / debian-esque. The Debian Python team uses a control file for tests to run before build, [like this](https://salsa.debian.org/python-team/packages/python-anyio/-/blob/master/debian/tests/control). This has the benefit of a cleaner separation of testing requirements from app business logic requirements. You can still have a separate test suite if you want to [this way](https://salsa.debian.org/python-team/packages/python-anyio/-/blob/master/debian/tests/upstreamtestsuite3). We can do this in a separate Debian branch which doesn't have to interfere with your approach.
